rds.rdsinstance: Add storage autoscaling (MaxAllocatedStorage)
This parameter defines the upper limit to which Amazon RDS can automatically
scale the storage of the DB instance.

For more information about this setting, including limitations that apply
to it, see Managing capacity automatically with Amazon RDS storage autoscaling
(https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PIOPS.StorageTypes.html#USER_PIOPS.Autoscaling)
in the Amazon RDS User Guide.

Make rds.CreatePatch exclude AllocatedStorage if autoscaling is enabled,
and the requested AllocatedStorage is lower than was is currently
allocated.

This allows a user to manually scale *up* storage even if autoscaling is
enabled, and prevents crossplane from attempting to scale *down* if
AWS has performed autoscaling.

One problem is that this change silently ignores any attempts to manually
downscale when autoscaling is enabled. Since downscaling is not
supported and it is not possible to distinguish this from autoscaling, I
don't see any other solutions.

I have added tests to verify the logic for omitting StorageSize and the
up to date-test:

    --- FAIL: TestObserve (0.00s)
        --- FAIL: TestObserve/AutoscaledStorageIsUpToDate (0.00s)
            rdsinstance_test.go:354: r: -want, +got:
                  managed.ExternalObservation{
                        ResourceExists:          true,
                -       ResourceUpToDate:        true,
                +       ResourceUpToDate:        false,
                        ResourceLateInitialized: false,
                        ConnectionDetails:       nil,
                        Diff:                    "",
                  }
    --- FAIL: TestUpdate (0.00s)
        --- FAIL: TestUpdate/AutoscaleExcludeStorage (0.00s)
            rdsinstance_test.go:674: r: -want, +got:
                  interface{}(
                +       e"cannot modify RDS instance: AllocatedStorage must not be set when on a modify request when AWS has autoscaled the storage",
                  )

Signed-off-by: Carl Henrik Lunde <chlunde@ifi.uio.no>